### ISSUE TITLE
Not running when built from source

### ISSUE THREAD

**Issue by soumyaDghosh** [Huluti/Curtail#158]
I have built the curtail app from source, but when I run it, I get

````
(curtail:115660): Gtk-CRITICAL **: 00:38:04.792: Error building template class 'CurtailWindow' for an instance of type 'CurtailWindow': .:0:0 Invalid object type 'AdwBanner'
Traceback (most recent call last):
  File "/snap/curtail/current/usr/share/curtail/curtail/main.py", line 41, in do_activate
    self.win = CurtailWindow(application=self)
  File "/snap/curtail/current/usr/share/curtail/curtail/window.py", line 62, in __init__
    self.build_ui()
  File "/snap/curtail/current/usr/share/curtail/curtail/window.py", line 74, in build_ui
    self.menu_button.set_menu_model(window_menu)
AttributeError: 'NoneType' object has no attribute 'set_menu_model'
`````
This doesn't closes the app, it continues to run, like an infinite loop, but no window shows up. I am on Ubuntu 22.04, with latest versions of libadwaita and gtk4

**Comment by Huluti** [comment]
AdwBanner is available with libadwaita 1.3. Ubuntu has 1.2...
